image: dsteinhoefel/islearn:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --no-deps -r requirements.txt
  - pip install z3-solver==4.8.14

test:
  script:
    - python3 -m pytest -n 16 --html=report.html --self-contained-html
      #- pip install tox
      #- tox -e py310

build:
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
