image: dsteinhoefel/islearn:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - cat requirements.txt | grep -v z3 > requirements_noz3.txt
  - pip install --no-deps -r requirements_noz3.txt
  - pip install --prefix=$(python3 -m site --user-base) --no-deps -e .[tests]

test:
  script:
    - python3 -m pytest -n 16 --html=report.html --self-contained-html

build:
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
