image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - apt update && apt install -y clang python3-dev curl
  - curl -L https://github.com/Clever/csvlint/releases/download/v0.3.0/csvlint-v0.3.0-linux-amd64.tar.gz | tar xz --strip-components 1 && mv csvlint /bin/
  - csvlint --help  # Print out csvlint help for debugging
  - python -V  # Print out python version for debugging
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade build
  - pip install -e .[test]

test:
  script:
    - python3 -m pytest -n 16 --randomly-seed=0 --html=report.html --self-contained-html --cov-report xml:coverage.xml --cov-config=.coveragerc --cov=islearn tests/
  coverage: '/TOTAL *\d+ *\d+ *\d+(\.\d+)?%/'
  artifacts:
    when: always
    paths:
      - report.html
      - coverage.xml

build:
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
